version: "3"

services:
  node:
    image: node:20
    command: bash -c "npm install && npm run build"
    working_dir: /app
    volumes:
      - .:/app
  app:
    build: .
    container_name: app
    command: bash -c "php artisan key:generate && php artisan migrate && php-fpm"
    restart: unless-stopped
    ports: 
      - 8000:8000
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_DATABASE=itjobs
      - DB_USERNAME=itjobs
      - DB_PASSWORD=itjobs
    volumes:
      - ./:/var/www
    depends_on:
      - node
      - db
    networks:
      - itjobs-backend-tier

  db:
    image: postgres:14
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - itjobs-backend-tier
    volumes:
      - itjobs-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=itjobs
      - POSTGRES_PASSWORD=itjobs

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - itjobs-backend-tier
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - itjobs-backend-tier

volumes:
  itjobs-db:
    driver: local

networks:
  itjobs-backend-tier:
    driver: bridge